### ISSUE TITLE
Deploy Gmomie on server

### ISSUE THREAD

**Issue by MarkDurrheim** [sl1msn1per/gnomie#5]
- [x] Create pipeline to push to production (Liam) {2hrs}
- [x] Monitor status (Liam) {5min}
- [x] Logger (Liam) {30min}

**Comment by sl1msn1per** [comment]
I'm going to work on "Logger".

**Comment by sl1msn1per** [comment]
I'll let the "uptime" encapsulate the status for the alpha release, later I'll want to have a thread which periodically polls disk space, etc.

**Comment by sl1msn1per** [comment]
The "pipeline to push to production" is going to be a set of scripts on the server (specific details confidential).
